DATABASE_URL='postgresql://neondb_owner:npg_R0S8VftjumKU@ep-sparkling-flower-a1aavnph-pooler.ap-southeast-1.aws.neon.tech/neondb?sslmode=require&channel_binding=require'

NEXT_PUBLIC_FILESERVER_URL='https://file.pasarjaya.cloud/api/upload'

NEXT_PUBLIC_CLERK_PUBLISHABLE_KEY=pk_test_bWFpbi1jaGVldGFoLTguY2xlcmsuYWNjb3VudHMuZGV2JA
CLERK_SECRET_KEY=sk_test_D5wK0VR5aJGsZlcbYJ8M86xAhTbz3IeEbAFQyx16s3

NEXT_PUBLIC_CLERK_SIGN_IN_URL=/sign-in
NEXT_PUBLIC_CLERK_SIGN_IN_FALLBACK_REDIRECT_URL=/
NEXT_PUBLIC_CLERK_SIGN_UP_FALLBACK_REDIRECT_URL=/