// const navigationItems = [
//   { href: "/", label: "Home" },
//   { href: "/dashboard", label: "Dashboard" },
//   { href: "/dashboard/roles", label: "Roles" },
//   { href: "/dashboard/clerk", label: "Clerk" },
//   { href: "/dashboard/users", label: "Users" },
//   { href: "/dashboard/academicyear", label: "Tahun Akademik" },
//   { href: "/dashboard/majors", label: "Jurusan" },
//   { href: "/dashboard/classes", label: "Kelas" },
//   { href: "/dashboard/subjects", label: "Mata Pelajaran" },
//   { href: "/dashboard/schedules", label: "Jadwal Pelajaran" },
//   { href: "/dashboard/attendance", label: "Absensi" },
//   { href: "/dashboard/typeviolations", label: "Jenis Pelanggaran" },
//   { href: "/dashboard/violations", label: "Pelanggaran" },
//   { href: "/dashboard/payments", label: "Pembayaran" },
//   { href: "/teacher/schedule", label: "Schedule for Teacher" },
//   { href: "/dashboard/specialschedule", label: "Special Schedule" },
//   { href: "/student/attendance/cmftrvnq5000lgq1tauteunhn", label: "Attendance for Student" },
//   { href: "/student/schedule/cmftrvnq5000lgq1tauteunhn", label: "Schedule for Student" },
//   { href: "/dashboard/calender", label: "Calendar for user" },
//   { href: "/dashboard/violations/student", label: "Pelanggaran for Siswa" },
//   { href: "/dashboard/violations/teacher", label: "Pelanggaran for teacher" },
//   { href: "/dashboard/parent", label: "Parent Page" },
// ];

